# Prepare data

## Load data

```{r load_read_counts, warning=FALSE, comments="", message=FALSE}
read_counts <- read_tsv("resources/coverm/genome.count.tsv.xz")
```

```{r load_genome_coverage, warning=FALSE, comments="", message=FALSE}
genome_coverage <- read_tsv("resources/coverm/genome.covered_bases.tsv.xz")
```

```{r load_taxonomy, warning=FALSE, comments="", message=FALSE}
taxonomy <- read_tsv("resources/gtdbtk/gtdbtk.summary.tsv.xz") %>%
  select(mag_id = user_genome, classification) %>%
  separate(
    classification,
    into = c("domain", "phylum", "class", "order", "family", "genus", "species"),
    sep = ";"
  )
```

```{r load_genome_quality, warning=FALSE, comments="", message=FALSE}
checkm2 <- read_tsv("resources/checkm2/quality_report.tsv.xz") %>%
  select(
    mag_id = Name, completeness = Completeness, contamination = Contamination,
    genome_size = Genome_Size, gc_content = GC_Content
  )
```

```{r load_genome_tree, warning=FALSE, comments="", message=FALSE}
genome_tree <- read_tree("resources/gtdbtk/gtdbtk.backbone.bac120.classify.tree")
```

## Create working objects




## Prepare color scheme



