# Differential abundance

```{r load_data_differential}
load("resources/data.Rdata")
```

## Create phyloseq object

```{r phyloseq_object, comment="", message=FALSE, warning=FALSE}
# phyloseq object considering structual zeros
phylo_samples <- sample_metadata %>%
  column_to_rownames("sample") %>%
  sample_data() # convert to phyloseq sample_data object

phylo_genome <- genome_counts %>%
  column_to_rownames("genome") %>%
  mutate_all(~ replace(., . == 0, 0.00001)) %>% # add pseudo counts to avoid structural zero issues (note this approach can be improved!)
  otu_table(., taxa_are_rows = TRUE)

phylo_taxonomy <- genome_metadata %>%
  filter(genome %in% rownames(phylo_genome)) %>% # remove structural zeros
  mutate(genome2 = genome) %>% # create a pseudo genome name column
  column_to_rownames("genome2") %>%
  dplyr::select(domain, phylum, class, order, family, genus, species, genome) %>% # add an additional taxonomic level to ensure genome-level analysis (as no all genomes have species-level taxonomic assignments. Otherwise, ANCOMBC2 aggregates analyses per species)
  as.matrix() %>%
  tax_table() # convert to phyloseq tax_table object

phyloseq <- phyloseq(phylo_genome, phylo_taxonomy, phylo_samples)
```

## Run ANCOMBC2

```{r ancom_model, comment="", message=FALSE, warning=FALSE, eval=FALSE}
set.seed(1234) # set seed for reproducibility
differential_abundance <- ancombc2(
  data = phyloseq,
  assay_name = "counts",
  tax_level = NULL, # change to agglomerate analysis to a higher taxonomic range
  fix_formula = "type", # fixed variable(s)
  rand_formula = "(1|individual)",
  p_adj_method = "holm",
  pseudo_sens = TRUE,
  prv_cut = 0.10,
  lib_cut = 0,
  s0_perc = 0.05,
  group = NULL,
  struc_zero = FALSE,
  neg_lb = FALSE,
  alpha = 0.05,
  n_cl = 2,
  verbose = TRUE,
  global = FALSE,
  pairwise = FALSE,
  dunnet = FALSE,
  trend = FALSE,
  iter_control = list(tol = 1e-5, max_iter = 20, verbose = FALSE),
  em_control = list(tol = 1e-5, max_iter = 100),
  lme_control = lme4::lmerControl(),
  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
  trend_control = NULL
)
```

## Plot results

```{r ancom_stats, comment="", message=FALSE, warning=FALSE, eval=FALSE}
tax <- data.frame(phyloseq@tax_table) %>%
  rownames_to_column(., "taxon")

differential_abundance_table <- differential_abundance$res %>%
  dplyr::select(genome=taxon, lfc_typefeces, p_typefeces) %>%
  filter(p_typefeces < 0.05) %>%
  dplyr::arrange(p_typefeces) %>%
  merge(., tax, by = "genome")

```

```{r ancombc_plot, comment="", message=FALSE, warning=FALSE}
ggplot(differential_abundance_table, aes(x = forcats::fct_rev(genome), y = lfc_typefeces, color = phylum)) +
  geom_point(size = 4) +
  scale_color_manual(values = phylum_colors[-c(3,4)]) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  facet_grid(phylum ~ ., scales = "free", space = "free") +
  theme(
    panel.background = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
    axis.title.x = element_blank(),
    strip.background = element_blank(), 
    strip.text = element_blank()
  ) +
  xlab("Genome") +
  ylab("log2FoldChange") +
  guides(col = guide_legend("Phylum"))
```

```{r ancom_rand_volcano, comment="", message=FALSE, warning=FALSE}
ancom_result <- differential_abundance$res %>%
  na.omit() %>%
  dplyr::select(genome=taxon, lfc_typefeces, p_typefeces) %>%
  left_join(genome_metadata, by = join_by(genome == genome))
ancom_result %>%
  mutate(significance = ifelse(p_typefeces < 0.05, "1", "0")) %>%
  ggplot(., aes(x = lfc_typefeces, y = -log(p_typefeces), color = significance)) +
  geom_point() +
  xlim(c(-10,4)) +
  scale_color_manual(values = c("#cccccc", "#00FFFF")) +
  geom_text(aes(3, 1), label = "Enriched\nin cloaca", color = "#666666") +
  geom_text(aes(-4, 1), label = "Enriched\nin faeces", color = "#666666") +
  labs(color = "Significance", y = "Difference between behaviours", x = "p-value") +
  theme_classic()
```
